---
- hosts: all
  become: yes
  tasks:
    - name: i want to install openjdk 8 on ubuntu node
      apt:
        name: "{{myjavapackageversion}}"
        state: present
     # when: ansible_os_family== "Debian"